DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS PUBLISHER;
DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR (
  AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL_ADDRESS VARCHAR(50) NOT NULL UNIQUE,
  DOB DATE NOT NULL
);

CREATE TABLE PUBLISHER (
  PUBLISHER_ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  TELEPHONE VARCHAR(10) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL
);

CREATE TABLE BOOK (
  ISBN VARCHAR(17) PRIMARY KEY,
  TITLE VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  VISIBLE BOOLEAN NOT NULL,  
  CREATION_DATE DATE NOT NULL,  
  AUTHOR_ID INT NOT NULL,
  PUBLISHER_ID INT,
  CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
  CONSTRAINT FK_BOOK_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID) 
);


